server:
  port: 8080

spring:
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: fasstowes
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  r2dbc:
    url: r2dbc:mysql//localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: fasstowes
#    pool:
#      initial-size: 2
#      max-size: 5
#      max-idle-time: 30m
#      validation-query: SELECT 1

# bind parameter 로깅 on
#logging.level.org.hibernate.type.descriptor.sql: trace
#logging.level.org.springframework.data.r2dbc: DEBUG
logging:
  level:
    org.springframework.data.r2dbc: DEBUG